- setup.py
- src/design/plone/contenttypes/setuphandlers.py
- src/design/plone/contenttypes/utils.py
Note per @deodorhunter per i prossimi lavori ;)
- Se un pacchetto ha delle dipendenze con altri, allora bisogna segnarle nel setup.py
- Lo script di creazione dei contenuti generava gli id a mano e male..plone.api fa tutto da solo e bene, basta passargli il titolo
> fix dipendenze e script di init

- src/design/plone/contenttypes/__init__.py
- src/design/plone/contenttypes/patches/__init__.py
- src/design/plone/contenttypes/patches/baseserializer.py
- src/design/plone/contenttypes/restapi/services/types/get.py
- src/design/plone/contenttypes/tests/test_base_serializer.py
In qualche caso ho visto che categorizzazione non lo mette come secondo tab.
In realtà quello che vogliamo noi è che "Correlati" sia sempre il secondo, dopo "Default".
Modificato di conseguenza.
> Us 11201 riordinare tabs

- src/design/plone/contenttypes/__init__.py
- src/design/plone/contenttypes/patches/__init__.py
- src/design/plone/contenttypes/patches/baseserializer.py
- src/design/plone/contenttypes/tests/test_base_serializer.py
we need it 'cause we could have a page type != from portal_type, eg. news are "comunicati stampa" or "notizie" or "avvisi"
> customize base serializer to add a meta type with the current object type

- src/design/plone/contenttypes/controlpanels/vocabularies.py
- src/design/plone/contenttypes/locales/design.plone.contenttypes.pot
- src/design/plone/contenttypes/locales/en/LC_MESSAGES/design.plone.contenttypes.po
- src/design/plone/contenttypes/locales/it/LC_MESSAGES/design.plone.contenttypes.po
- src/design/plone/contenttypes/restapi/configure.zcml
- src/design/plone/contenttypes/restapi/types/adapters.py
- src/design/plone/contenttypes/restapi/types/configure.zcml
- src/design/plone/contenttypes/tests/test_content_types.py
- src/design/plone/contenttypes/tests/test_vocabularies.py
- src/design/plone/contenttypes/vocabularies/configure.zcml
- src/design/plone/contenttypes/vocabularies/controlapanel_vocabularies.py
nella forma "portal_type|WxH", in questo modo analogamente a come si fa customizzando la description di un campo personalizzando i form di Add/Edit, customizziamo il messaggio tramite restapi.
Avere il vocabolario nel controlpanel rende veloce fare nuove customizzazioni. 
Il messaggio per ora si aggiunge solo se c'è il tipo corrispondente a control panel: è un meccanismo analogo alle dimensioni delle minuature; un po' raw, ma come per quelle, devi sapere cosa stai facendo.
Fra l'altro fatta in questo modo, ogni cliente per ogni contenttype indica la sua immagine.
> [new] aggiunta la possibilità di mettere nel registry le dimensioni delle immagini per i contenttype

- src/design/plone/contenttypes/restapi/services/types/get.py
- src/design/plone/contenttypes/tests/test_content_types.py
Fix dei fieldset per Document e Unita' Organizzativa, che impedivano l'aggiunta su Volto dei CT. 
Disabilitato i test sui fieldset per questi due CT.
> Fix fieldsets document and UnitaOrganizzativa

- README.md
- src/design/plone/contenttypes/restapi/serializers/configure.zcml
- src/design/plone/contenttypes/restapi/serializers/relationfield.py
- src/design/plone/contenttypes/tests/test_relateditems_with_dates.py
Con questa modifica, l'endpoint ritorna informazioni extra per i vari contenuti correlati dei ct:
- effective: la data di pubblicazione
- start, end: data di inizio e fine evento
> date nei correlati

- base.cfg
- src/design/plone/contenttypes/behaviors/configure.zcml
- src/design/plone/contenttypes/behaviors/trasparenza.py
- src/design/plone/contenttypes/browser/configure.zcml
- src/design/plone/contenttypes/browser/trasparenza.py
- src/design/plone/contenttypes/profiles/default/types/Document.xml
- src/design/plone/contenttypes/profiles/default/types/Servizio.xml
- src/design/plone/contenttypes/restapi/services/configure.zcml
- src/design/plone/contenttypes/restapi/services/trasparenza/configure.zcml
- src/design/plone/contenttypes/restapi/services/trasparenza/get.py
- src/design/plone/contenttypes/restapi/services/types/get.py
- src/design/plone/contenttypes/tests/test_ct_servizio.py
- test_plone52.cfg
aggiunti un behavior per amministrazione trasparente nei servizi
aggiunto un service @trasparenza-items per recuperare l'alberatura fino al secondo livello per la pagina principale dell'amministrazione trasparente
aggiunto un service @trasparenza per recuperare le info per la creazione della pagina dinamica contenente i dettagli dei procedimenti
aggiunte due viste per avere. diversi layout del CT Document al servizio di pagine specifiche dell'amministrazione trasparente
> Us 13953 amministrazione trasparente

- CHANGES.rst
- src/design/plone/contenttypes/profiles/default/metadata.xml
- src/design/plone/contenttypes/profiles/default/types/CartellaModulistica.xml
- src/design/plone/contenttypes/tests/test_ct_cartella_modulistica.py
- src/design/plone/contenttypes/upgrades/configure.zcml
- src/design/plone/contenttypes/upgrades/upgrades.py
All'interno di un contenuto di tipo CartellaModulistica è ora possibile aggiungere anche File.
> Cartella modulistica enable file

- CHANGES.rst
- src/design/plone/contenttypes/restapi/serializers/bando.py
[fix] attachments folders inside bando now are returned in parent actual order instead than being sorted by title
> Fix ordinamento bandi, us 24062

- CHANGES.rst
- src/design/plone/contenttypes/interfaces/servizio.py
- src/design/plone/contenttypes/restapi/deserializers/configure.zcml
- src/design/plone/contenttypes/restapi/deserializers/dxfields.py
- src/design/plone/contenttypes/restapi/serializers/configure.zcml
- src/design/plone/contenttypes/restapi/serializers/dxfields.py
- src/design/plone/contenttypes/restapi/types/adapters.py
- src/design/plone/contenttypes/restapi/types/configure.zcml
- src/design/plone/contenttypes/tests/test_ct_servizio.py
- test_plone60.cfg
Essendo un campo che deve poter essere sia un link interno che esterno, è meglio gestirlo come il campo degli oggetti Link.
In questo modo sia da Plone che da Volto è possibile usare il widget per generarli entrambi, e restapi gestisce la serializzazione/deserializzazione in maniera trasparente.
Questo è un campo nuovo o che va convertito in fase di migrazione?
> fix canale_digitale_link field type and restapi integration

- CHANGES.rst
- src/design/plone/contenttypes/restapi/serializers/configure.zcml
- src/design/plone/contenttypes/restapi/serializers/dxfields.py
- src/design/plone/contenttypes/testing.py
I don't know why i deleted it in a previous commit: https://github.com/RedTurtle/design.plone.contenttypes/commit/82165bbfc78297bf4de7ed08513ae967860df48d#diff-6e50b93b7290fe986ded61f0042da6cdc5d55a7a36701c95bbe97c7b08baa939
> Re-add FileFieldViewModeSerializer accidentally deleted

- CHANGES.rst
- src/design/plone/contenttypes/browser/utils/check_eventi.py
Improved "Buone pratiche" view for Event: checking both for relation with Venue and coordinates.
> Improved "Buone pratiche" view for Event - US #49677

- CHANGES.rst
- src/design/plone/contenttypes/restapi/serializers/dxfields.py
- src/design/plone/contenttypes/tests/test_filefield_view_mode_serializer.py
needed for a future feature that will show file size and meta-type in blocks, links, etc
> Add getObjSize info in File field serializer

- CHANGES.rst
- README.md
- src/design/plone/contenttypes/controlpanels/settings.py
- src/design/plone/contenttypes/restapi/services/configure.zcml
- src/design/plone/contenttypes/restapi/services/navigation/configure.zcml
- src/design/plone/contenttypes/restapi/services/navigation/get.py
- src/design/plone/contenttypes/tests/test_custom_service_navigation.py
- src/design/plone/contenttypes/upgrades/configure.zcml
Add new flag in settings needed to choose to show or not auto-generated footer columns and Customize @navigation endpoint to expose also the new flag for frontend
> Make footer columns auto-generation optional

- CHANGES.rst
- src/design/plone/contenttypes/browser/utils/change_news_type.py
- src/design/plone/contenttypes/browser/utils/templates/utils.pt
- src/design/plone/contenttypes/tests/test_change_news_type.py
- test_plone60.cfg
dal momento in cui si utilizza collective.taxonomy, i valori vengono indicizzati solo se sono all'interno del vocabolario della tassonomia. in questo caso tipologia_notizia.
Il che significa che change_news_types non presenta tutti i valori possibili perchè non sono a catalogo.
Il che significa che l'unico modo per far funzionare questa vista è prendere i valori delle tipologie dall'oggetto news.
e poi iterare sugli oggetti news per fare la modifica.
@folix-01 chiedo a te giusto perché conosci bene la vista
> fix change_news_type

- CHANGES.rst
- src/design/plone/contenttypes/restapi/serializers/summary.py
- src/design/plone/contenttypes/tests/test_summary_serializer.py
quando si crea un evento rassegna con eventi figli, i figli non hanno data di inizio.
si decide di partire con la start date nel summary
> Add date to events in items

- .pre-commit-config.yaml
- CHANGES.rst
- src/design/plone/contenttypes/restapi/serializers/summary.py
- src/design/plone/contenttypes/restapi/services/types/get.py
aggiunta del campo importi_viaggi_servizio a blocchi all'interno dell'incarico
> Add importi_viaggi_servizio as block field in Incarico response

- CHANGES.rst
- src/design/plone/contenttypes/restapi/serializers/dxfields.py
- src/design/plone/contenttypes/tests/test_ct_servizio.py
DTD is asking to change the behavior when the 'access the service' button is pressed. They don't want to see 'unauthorized,' but rather they want an 'access' label, which can be obtained using /login. For this reason, we want to ensure that if the current user doesn't have permission to view the target of the 'access the service' button, a link with /login will be used instead.
> update canale_digitale_link serializer

- CHANGES.rst
- src/design/plone/contenttypes/behaviors/multi_file.py
Set  field as primary, so we call @@download on the content, that file will be downloaded automatically.
> Backport of #268 on v5.x

- CHANGES.rst
- src/design/plone/contenttypes/events/common.py
now try to reindex children only if context is folderish 🤦‍♂️
> Avoid acquisition problem in *onModify* event handler

- CHANGES.rst
- README.md
- src/design/plone/contenttypes/profiles/default/metadata.xml
- src/design/plone/contenttypes/profiles/default/types/Documento.xml
- src/design/plone/contenttypes/restapi/serializers/documento.py
- src/design/plone/contenttypes/tests/test_ct_documento.py
- src/design/plone/contenttypes/upgrades/configure.zcml
- src/design/plone/contenttypes/upgrades/to_730x.py
Gli editor hanno necessità di poter tagliare / incollare contenuti all'interno del ct documento.
Si vuole cambiare le cose il meno possibile rispetto alla situazione attuale per cui aggiungo il file ma lo nascondo nel menu aggiungi del frontend
> Us64414 uploda file in CT Documento

- CHANGES.rst
- src/design/plone/contenttypes/profiles/default/metadata.xml
- src/design/plone/contenttypes/upgrades/configure.zcml
- src/design/plone/contenttypes/upgrades/to_730x.py
otherwise these are available only for new sites
> Add upgrade-step to add missing metadata for image captions

- CHANGES.rst
- src/design/plone/contenttypes/upgrades/to_730x.py
Fix the last upgrade step that wrongly update and override all types
> update upgrades method

- CHANGES.rst
- src/design/plone/contenttypes/configure.zcml
- src/design/plone/contenttypes/indexers/configure.zcml
- src/design/plone/contenttypes/indexers/events.py
- src/design/plone/contenttypes/profiles/default/metadata.xml
- src/design/plone/contenttypes/profiles/default/registry/criteria.xml
- src/design/plone/contenttypes/profiles/to_7313/registry.xml
- src/design/plone/contenttypes/upgrades/configure.zcml
- src/design/plone/contenttypes/upgrades/to_730x.py
Aggiunto un indice "data di fine effettiva" degli eventi perchè il layer di redturtle.volto faceva cose con le date di inizio e fine evento. In questo modo calcoliamo in un indice la vera fine e possiamo ordinare per quella.
Tenendo conto anche delle ricorrenze.
> Us64153 fine effettiva

- CHANGES.rst
- src/design/plone/contenttypes/restapi/serializers/summary.py
La condition era sbagliata perchè and viene prima degli or, quindi ogni volta che apeertura_bando era in metadata_fields veniva azzerato.
ho prima sistemato con le giuste parentesi, poi per migliorare la lettura ho splittato su due if
> Bug data apertura summary bandi
