RedTurtle/design.plone.contenttypes

src/design/plone/contenttypes/interfaces/servizio.py
src/design/plone/contenttypes/tests/test_servizio.py

fix reference widget in frontend and add some test to chek it

Us 10890 servizio fix reference widget vari

---

src/design/plone/contenttypes/interfaces/servizio.py
src/design/plone/contenttypes/tests/test_servizio.py

Move relatedfields to correlati tab and adds test

Us 10893 servizio tab correlati

---

src/design/plone/contenttypes/profiles/default/types/Pagina_Argomento.xml
src/design/plone/contenttypes/tests/test_pagina_argomento.py

Aggiunto il behavior leadimage + test

Us 11503 leadimage argomento

---

README.md
src/design/plone/contenttypes/behaviors/configure.zcml
src/design/plone/contenttypes/behaviors/info_testata.py
src/design/plone/contenttypes/profiles/default/types/Document.xml
src/design/plone/contenttypes/restapi/services/types/get.py
src/design/plone/contenttypes/tests/test_content_types.py
src/design/plone/contenttypes/tests/test_documento.py

Da usare nelle pagine di disambiguazione

Aggiunta behavior per le info in testata

---

src/design/plone/contenttypes/behaviors/evento.py
src/design/plone/contenttypes/profiles/default/types/Event.xml
src/design/plone/contenttypes/restapi/services/types/get.py
src/design/plone/contenttypes/schema_overrides.py
src/design/plone/contenttypes/tests/test_event.py

modifica all'ordine dei campi. La cosa è temporanea perché bisogna fare al volo. 
Poi capiremo come gestire meglio.

Event view modifications

---

src/design/plone/contenttypes/behaviors/luogo.py

aggiunto il campo e' sede di al Luogo

[dev] added sede_di relation field to Venue

---

README.md
src/design/plone/contenttypes/behaviors/luoghi_correlati.py
src/design/plone/contenttypes/behaviors/strutture_correlate.py
src/design/plone/contenttypes/profiles/default/metadata.xml
src/design/plone/contenttypes/profiles/default/types/Event.xml
src/design/plone/contenttypes/restapi/services/types/get.py
src/design/plone/contenttypes/schema_overrides.py
src/design/plone/contenttypes/tests/test_content_types.py
src/design/plone/contenttypes/tests/test_ct_event.py
src/design/plone/contenttypes/upgrades.zcml

fix event fields

---

src/design/plone/contenttypes/restapi/services/types/get.py

Reverts RedTurtle/design.plone.contenttypes#46

Revert "move versionable fields into settings fieldset"

---

src/design/plone/contenttypes/indexers/configure.zcml
src/design/plone/contenttypes/indexers/events.py
src/design/plone/contenttypes/profiles/default/catalog.xml
src/design/plone/contenttypes/profiles/default/metadata.xml
src/design/plone/contenttypes/profiles/default/registry/criteria.xml
src/design/plone/contenttypes/upgrades.py
src/design/plone/contenttypes/upgrades.zcml
src/design/plone/contenttypes/vocabularies/configure.zcml
src/design/plone/contenttypes/vocabularies/events.py

Per ora ci serve poter filtrare per luogo correlato all'evento.
Espanderemo se richiesto.

Gestione ricerca luogo dell'evento

---

CHANGES.rst
src/design/plone/contenttypes/behaviors/configure.zcml

Ripristinata la behavior che era stata commentata un po' di tempo fa (#81 ).
---
(richiesta da tp#19415)

[chg] restored the behavior 'Trasparenza'

---

src/design/plone/contenttypes/restapi/serializers/summary.py

aggiunti alcuni controlli per evitare che si rompa

fix taxonomy (wip)

---

.github/workflows/flake8.yml
CHANGES.rst
src/design/plone/contenttypes/behaviors/evento.py
src/design/plone/contenttypes/browser/manage_content/check_servizi.py
src/design/plone/contenttypes/browser/manage_content/templates/check_servizi.pt
src/design/plone/contenttypes/patches/baseserializer.py
src/design/plone/contenttypes/profiles/default/metadata.xml
src/design/plone/contenttypes/profiles/default/types/UnitaOrganizzativa.xml
src/design/plone/contenttypes/testing.py
src/design/plone/contenttypes/upgrades/configure.zcml
src/design/plone/contenttypes/upgrades/upgrades.py

Cambiato lo schema dell'evento per far si che patrocinato da sia richtext e non plain text

Fix event schema

---

src/design/plone/contenttypes/upgrades/upgrades.py

Do not break if content doesn't have a language set

Fix default language in upgrade-step

---

src/design/plone/contenttypes/upgrades/to_7002.py

Extended mapping for backward compatibility

extended mapping for taxonomies

---

CHANGES.rst
setup.py
src/design/plone/contenttypes/browser/manage_content/change_news_type.py
src/design/plone/contenttypes/browser/manage_content/move_news_items.py
src/design/plone/contenttypes/interfaces/cartella_modulistica.py
src/design/plone/contenttypes/profiles/default/metadata.xml
src/design/plone/contenttypes/profiles/default/types/Venue.xml
src/design/plone/contenttypes/restapi/serializers/configure.zcml
src/design/plone/contenttypes/restapi/serializers/dxfields.py
src/design/plone/contenttypes/restapi/services/modulistica_items/get.py
src/design/plone/contenttypes/tests/test_change_news_type.py
src/design/plone/contenttypes/tests/test_ct_luogo.py
src/design/plone/contenttypes/tests/test_filefield_view_mode_serializer.py
src/design/plone/contenttypes/tests/test_move_news_items_view.py
src/design/plone/contenttypes/upgrades/configure.zcml
src/design/plone/contenttypes/upgrades/upgrades.py

Master to pnrr

---

src/design/plone/contenttypes/upgrades/to_7001.py

Check if contact_info exists before deleting it to avoid upgrade failure.

improved check

---

src/design/plone/contenttypes/restapi/serializers/relationfield.py

I think that it should be implemented by plone.restapi, but the urgency requires to make this change here

Handle None case return

---

src/design/plone/contenttypes/configure.zcml
src/design/plone/contenttypes/profiles/default/metadata.xml
src/design/plone/contenttypes/profiles/fix_syndication/registry.xml
src/design/plone/contenttypes/upgrades/configure.zcml
src/design/plone/contenttypes/upgrades/upgrades.py

create upgrade steps to fix plone6 mess up with ISiteSyndicationSettings

Fix syndication

---

CHANGES.rst
src/design/plone/contenttypes/browser/manage_content/check_servizi.py

rewrite delle url più generale al posto del semplice replace di /api

fix url nella pagina check_servizi

---

CHANGES.rst
src/design/plone/contenttypes/configure.zcml
src/design/plone/contenttypes/profiles/default/metadata.xml
src/design/plone/contenttypes/tests/test_ct_event.py
src/design/plone/contenttypes/tests/test_ct_news.py
src/design/plone/contenttypes/upgrades/configure.zcml
src/design/plone/contenttypes/upgrades/upgrades.py

…rrect SearchableText indexing

Fix event news indexing also on v5

---

src/design/plone/contenttypes/browser/manage_content/check_servizi.py
src/design/plone/contenttypes/interfaces/persona.py
src/design/plone/contenttypes/patches/patches.py
src/design/plone/contenttypes/upgrades/to_7001.py
src/design/plone/contenttypes/upgrades/to_7002.py
src/design/plone/contenttypes/upgrades/upgrades.py

fix: fix foto_persona helptext, fix flake8 errors

US 44750 helptext foto persona

---

.pre-commit-config.yaml
src/design/plone/contenttypes/browser/manage_content/templates/check_servizi.pt
src/design/plone/contenttypes/profiles/default/types/News_Item.xml
src/design/plone/contenttypes/profiles/default/types/Servizio.xml
src/design/plone/contenttypes/profiles/fix_syndication/registry.xml
src/design/plone/contenttypes/restapi/deserializers/documento.py
src/design/plone/contenttypes/restapi/deserializers/news.py
src/design/plone/contenttypes/restapi/deserializers/servizio.py
src/design/plone/contenttypes/restapi/deserializers/unitaorganizzativa.py
src/design/plone/contenttypes/restapi/serializers/dxfields.py
src/design/plone/contenttypes/restapi/serializers/summary.py
src/design/plone/contenttypes/restapi/types/adapters.py
src/design/plone/contenttypes/tests/test_ct_servizio.py
src/design/plone/contenttypes/upgrades/to_7001.py
src/design/plone/contenttypes/upgrades/upgrades.py
src/design/plone/contenttypes/vocabularies/reference_vocabularies.py
test-5.2.x-py27.cfg
tox.ini

durante la migrazione a PNRR spostati i file dalla cartella compensi e della cartella import di viaggio della persona  a dentro l'incarico

migrazione compensi e importi di viaggio

---

CHANGES.rst
src/design/plone/contenttypes/behaviors/evento.py

Come richiesto da asseverazione in corso

Costo dell'evento obbligatorio

---

CHANGES.rst
README.md
src/design/plone/contenttypes/browser/utils/check_notizie.py
src/design/plone/contenttypes/browser/utils/configure.zcml
src/design/plone/contenttypes/browser/utils/templates/check_notizie.pt
src/design/plone/contenttypes/browser/utils/templates/utils.pt

Added utility views: @@check-notizie and @@download-check-notizie

Added utility views for News - US #48468 

---

CHANGES.rst
src/design/plone/contenttypes/browser/utils/check_eventi.py
src/design/plone/contenttypes/browser/utils/check_notizie.py
src/design/plone/contenttypes/browser/utils/check_uo.py

Fixed check on Competenze field. Excluding expired events and news

---

CHANGES.rst
src/design/plone/contenttypes/indexers/configure.zcml
src/design/plone/contenttypes/indexers/servizio.py
src/design/plone/contenttypes/profiles/default/catalog.xml
src/design/plone/contenttypes/profiles/default/metadata.xml
src/design/plone/contenttypes/profiles/default/registry/criteria.xml
src/design/plone/contenttypes/upgrades/configure.zcml
src/design/plone/contenttypes/upgrades/upgrades.py

feat: added new indexer, catalog index and query operation for canale_digitale_link field of Servizio CT

US 50839 filtro canale digitale link servizi

---

CHANGES.rst
src/design/plone/contenttypes/browser/utils/check_servizi.py
src/design/plone/contenttypes/browser/utils/templates/check_servizi.pt

provides also the full list of servizi

Us 53140 elenco servizi

---

CHANGES.rst
src/design/plone/contenttypes/events/common.py
src/design/plone/contenttypes/profiles/default/metadata.xml
src/design/plone/contenttypes/tests/test_substructure_creation.py
src/design/plone/contenttypes/upgrades/configure.zcml
src/design/plone/contenttypes/upgrades/to_730x.py

come chiesto da nicola, alla fine delle n cose da fare rimaneva di rimuovere i file dalla cartella modulistica

remove file from addable types in servizio/modulistica folder

---

CHANGES.rst
src/design/plone/contenttypes/restapi/serializers/unita_organizzativa.py

This is a workaround for not returning null contact points.

Workaround for empty contacts UO summaryserializer

---

CHANGES.rst
setup.py
src/design/plone/contenttypes/browser/utils/templates/utils.pt

This need dependency with redturtle.volto>=5.5.3

Add link to find-broken-links in design-utils view.

---

CHANGES.rst
src/design/plone/contenttypes/restapi/serializers/summary.py
src/design/plone/contenttypes/tests/test_summary_serializer.py

Added fields end and recurrence to event summary serializer.

add field to event summary

---

CHANGES.rst
src/design/plone/contenttypes/browser/bando.py

Refactor **retrieveContentsOfFolderDeepening** to be compliant with https://github.com/RedTurtle/redturtle.bandi/pull/25

Modulo hook in BandoView

---

CHANGES.rst
src/design/plone/contenttypes/browser/utils/configure.zcml
src/design/plone/contenttypes/browser/utils/templates/utils.pt
src/design/plone/contenttypes/browser/utils/users.py
src/design/plone/contenttypes/browser/utils/users.zcml
test-6.0.x.cfg

Utility per scaricare l'elenco degli utenti in excel da usare per invio comunicazioni

users summary

---

CHANGES.rst
src/design/plone/contenttypes/interfaces/unita_organizzativa.py

cambiato il numero di assessori di riferimento

Unità organizzativa con due Assessori di riferimento

---

src/design/plone/contenttypes/events/common.py
src/design/plone/contenttypes/profiles/default/metadata.xml
src/design/plone/contenttypes/tests/test_substructure_creation.py
src/design/plone/contenttypes/upgrades/configure.zcml
src/design/plone/contenttypes/upgrades/to_730x.py

Cartelle aggiuntive all'interno della persona per inserire emolumenti e dichiarazioni di insussistenza

Cartelle aggiuntive all'interno della persona

---

CHANGES.rst
src/design/plone/contenttypes/adapters/configure.zcml
src/design/plone/contenttypes/profiles/default/metadata.xml
src/design/plone/contenttypes/upgrades/configure.zcml
src/design/plone/contenttypes/upgrades/upgrades.py
test_plone52.cfg

indicizzazione dei contenuti del blocco "info", verificare se serve anche sul main (testato su v3 il blocco info non c'è quindi non si applica)

info searchable
